services:
  mongodb-central:
    image: 'mongo'
    ports: 
      - 27017:27017
    volumes:
      - data:/data/db

  mongodb-1:
    image: 'mongo'
    ports: 
      - 27018:27017
    volumes:
      - data1:/data/db

  mongodb-2:
    image: 'mongo'
    ports: 
      - 27019:27017
    volumes:
      - data2:/data/db

  mongodb-3:
    image: 'mongo'
    ports: 
      - 27020:27017
    volumes:
      - data3:/data/db

  central:
    image: filipmilo/central
    ports: 
      - 3000:3000
    environment: 
      - DB=${LIBRARY_1_DB}
    depends_on: 
      - mongodb-central

  library1:
    image: filipmilo/lib1
    ports:
      - 8000:8000
    environment: 
      - LIBRARY=${LIBRARY_1}
      - DB=${LIBRARY_1_DB}
    depends_on: 
      - mongodb-1

  library2:
    image: filipmilo/lib2
    ports:
      - 8001:8000
    environment: 
      - LIBRARY=${LIBRARY_2}
      - DB=${LIBRARY_2_DB}
    depends_on: 
      - mongodb-2

  library3:
    image: filipmilo/lib3
    ports:
      - 8002:8000
    environment: 
      - LIBRARY=${LIBRARY_3}
      - DB=${LIBRARY_3_DB}
    depends_on: 
      - mongodb-3

volumes:
  data:
  data1:
  data2:
  data3:
