apiVersion: apps/v1
kind: Deployment
metadata:
  name: lib1-deployment 
spec:
  selector:
    matchLabels:
      app: lib1 
  template:
    metadata:
      labels:
        app: lib1
    spec:
      containers:
      - name: library1
        image: filipmilo/lib1
        env:
        - name: LIBRARY
          value: "Novi Sad"
        - name: DB
          value: "mongodb://mongodb-1:27017/db"
        ports:
        - containerPort: 8000
      - name: mongodb-1
        image: mongo
        ports:
        - containerPort: 27017
