apiVersion: apps/v1
kind: Deployment
metadata:
  name: lib1-deployment 
spec:
  selector:
    matchLabels:
      app: lib1 
  template:
    metadata:
      labels:
        app: lib1
    spec:
      containers:
      - name: library1
        image: filipmilo/lib1
        env:
        - name: LIBRARY
          value: "Novi Sad"
        - name: DB
          value: "mongodb://localhost:27017/db"
        - name: NODE_ENV
          value: "prod"
        - name: PATH
          value: "lib1"
        ports:
        - containerPort: 8000
          name: lib1-port
      - name: mongodb-1
        image: mongo
        volumeMounts:
          - mountPath: app/lib1
            name: lib1-volume
        ports:
        - containerPort: 27017
      volumes:
        - name: lib1-volume
          persistentVolumeClaim: 
            claimName: host-pvc
