apiVersion: apps/v1
kind: Deployment
metadata:
  name: lib3-deployment 
spec:
  selector:
    matchLabels:
      app: lib3
  template:
    metadata:
      labels:
        app: lib3
    spec:
      containers:
      - name: library3
        image: filipmilo/lib3:prod
        env:
        - name: LIBRARY
          value: "Nis"
        - name: DB
          value: "mongodb://localhost:27017/db"
        - name: NODE_ENV
          value: "prod"
        ports:
        - containerPort: 8000
          name: lib3-port
      - name: mongodb-3
        image: mongo
        volumeMounts:
          - mountPath: app/lib3
            name: lib3-volume
        ports:
        - containerPort: 27017
      volumes:
        - name: lib3-volume
          persistentVolumeClaim: 
            claimName: host-pvc
