name: Publish workflow
run-name: ${{ github.actor }} is building and pushing the app to DockerHub
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag and push the Central image to DockerHub
        env: 
          REPOSITORY: central
          IMAGE_TAG: latest
        run: |
          docker build -t $REPOSITORY:$IMAGE_TAG ./central

          docker push $REPOSITORY:$IMAGE_TAG
