name: Publish workflow
run-name: ${{ github.actor }} is building and pushing the app to DockerHub
on: [push]
jobs:
  central:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag and push the Central image to DockerHub
        env: 
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
          REPOSITORY: central
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./central
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  lib1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag and push the Lib1 image to DockerHub
        env: 
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
          REPOSITORY: lib1
          IMAGE_TAG: latest
        run: |
          echo ${{ secrets.LIB1 }} >> .env.lib1
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --build-arg env = .env.lib1 ./central
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  lib2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag and push the Lib1 image to DockerHub
        env: 
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
          REPOSITORY: lib2
          IMAGE_TAG: latest
        run: |
          echo ${{ secrets.LIB2 }} >> .env.lib2
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --build-arg env = .env.lib2 ./central
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  lib3:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag and push the Lib3 image to DockerHub
        env: 
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
          REPOSITORY: lib3
          IMAGE_TAG: latest
        run: |
          echo ${{ secrets.LIB3 }} >> .env.lib3
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --build-arg env = .env.lib3 ./central
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
