name: Publish workflow
run-name: ${{ github.actor }} is building and pushing the app to DockerHub
on: [push]
jobs:
  central:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag and push the Central image to DockerHub
        env: 
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
          REPOSITORY: central
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./central
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  lib1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag and push the Lib1 image to DockerHub
        env: 
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
          REPOSITORY: lib1
          IMAGE_TAG: latest
          LIBRARY: Novi Sad
          PORT: 8000
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            --build-arg VITE_LIBRARY=$LIBRARY \
            --build-arg VITE_PORT=$PORT \
            ./library

          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  lib2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag and push the Lib1 image to DockerHub
        env: 
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
          REPOSITORY: lib2
          IMAGE_TAG: latest
          LIBRARY: Beograd 
          PORT: 8001
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            --build-arg VITE_LIBRARY=$LIBRARY \
            --build-arg VITE_PORT=$PORT \
            ./library
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  lib3:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag and push the Lib3 image to DockerHub
        env: 
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
          REPOSITORY: lib3
          IMAGE_TAG: latest
          LIBRARY: Nis
          PORT: 8002
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            --build-arg VITE_LIBRARY=$LIBRARY \
            --build-arg VITE_PORT=$PORT \
            ./library

          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
